/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Nathan
 */
public class VueConnect extends javax.swing.JFrame {

    /**
     * Creates new form Connect
     */
    public VueConnect() {
        initComponents();
        // Definition de la taille de la fenetre
        double a, b;
//        Toolkit t = this.getToolkit();
//        Dimension d = t.getScreenSize();
//        a = d.getWidth() * 0.4;
//        b = d.getHeight() * 0.4;
//        Dimension c = new Dimension(((int) a), ((int) b));
//        this.setSize(c);
        this.setResizable(false);
        this.setLocationRelativeTo(null);// PERMET DE CENTRER LA FENETRE
        Ident.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if(Ident.getText().equals("Identifiant")){
                Ident.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                    if(Ident.getText().equals("")){
                        Ident.setText("Identifiant");
                    }
            }

        });

        mdp.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if(mdp.getText().equals("mdp")){
                mdp.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                    if(mdp.getText().equals("")){
                        mdp.setText("mdp");
                    }
            }

        });
        
    



 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Ident = new javax.swing.JTextField();
        mdp = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 620));

        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/valider.png"))); // NOI18N
        jButton1.setText("SE CONNECTER");
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 380, 160, 50);

        Ident.setText("Identifiant");
        jPanel1.add(Ident);
        Ident.setBounds(550, 250, 140, 30);

        mdp.setText("mdp");
        jPanel1.add(mdp);
        mdp.setBounds(550, 310, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("CONNEXION");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(500, 170, 170, 40);

        jLabel2.setText("Login");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(490, 250, 40, 40);

        jLabel3.setText("mdp");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(490, 310, 30, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondecran1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1090, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueConnect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ident;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField mdp;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JButton getButton() {
        return jButton1;
    }
    
    public String getTextIdentifiant(){
        return this.Ident.getText();
    }
    public String getTextMDP(){
        return this.mdp.getText();
    }

    public JTextField getIdent() {
        return Ident;
    }
    public void resetChamps(){
        mdp.setText("mdp");
        Ident.setText("Identifiant");
        
        
    }

 

    public JPasswordField getMdp() {
        return mdp;
    }
    
    
}
